# REMINDER: .env file has secret keys. NEVER upload it to GitHub.
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Optional
from uuid import uuid4
from chatbot import get_answer
from database import get_supabase

# STEP 1: Create the FastAPI app instance
# This is the main application object everything connects to
app = FastAPI(
    title="Restaurant Chatbot API",
    description="Multi-tenant RAG chatbot backend for restaurants",
    version="1.0.0"
)

# STEP 2: Define the shape of data coming IN and going OUT
# Pydantic models validate the data automatically
# If frontend sends wrong data type FastAPI rejects it immediately

class ChatRequest(BaseModel):
    # The message the customer typed in the chatbot
    message: str
    
    # Which restaurant this customer is chatting with
    restaurant_id: str
    
    # Unique ID for this customer session
    # Optional because on first message frontend may not have one yet
    # If not provided the server generates one automatically
    session_id: Optional[str] = None


class ChatResponse(BaseModel):
    # The natural language answer generated by Groq
    answer: str
    
    # The raw list of matching dishes for frontend to render as cards
    dishes: list
    
    # The session ID to send back on every next message
    # Frontend must store this and include it in every request
    session_id: str


class HealthResponse(BaseModel):
    # Simple status field to confirm server is running
    status: str
    
    # Short message with extra info
    message: str

# STEP 3: Health check endpoint
# Render calls this automatically every few minutes
# to verify the server is alive and running
# If this does not return 200 OK Render will restart the server

@app.get("/health", response_model=HealthResponse)
async def health_check():
    # Simply return ok status — no logic needed here
    return {
        "status": "ok",
        "message": "Restaurant chatbot API is running"
    }

# STEP 4: Menu endpoint
# Returns the full menu for a specific restaurant
# Frontend calls this to display all dishes before chat starts
# restaurant_id comes directly from the URL
# Example: GET /menu/rest_delhi_01

@app.get("/menu/{restaurant_id}")
async def get_menu(restaurant_id: str):
    
    # Wrap in try except so server never crashes on bad requests
    try:
        print(f"Fetching full menu for restaurant: {restaurant_id}")
        
        supabase = await get_supabase()
        response = await supabase.table("menu_items").select(
            "name, description, price, cuisine, is_veg, "
            "spice_level, allergens, ingredients"
        ).eq("restaurant_id", restaurant_id).execute()
        
        # If no dishes found for this restaurant_id
        if not response.data:
            raise HTTPException(
                status_code=404,
                detail=f"No menu found for restaurant: {restaurant_id}"
            )
        
        print(f"Found {len(response.data)} dishes for {restaurant_id}")
        
        # Return the list of dishes directly
        return {
            "restaurant_id": restaurant_id,
            "total_dishes": len(response.data),
            "menu": response.data
        }
    
    except HTTPException:
        # Re-raise HTTP exceptions as they are already formatted
        raise
    
    except Exception as e:
        print(f"Error fetching menu: {e}")
        raise HTTPException(
            status_code=500,
            detail="Failed to fetch menu. Please try again."
        )

# STEP 5: Main chat endpoint
# This is the core endpoint the frontend uses for every message
# Frontend sends the customer message and gets the answer back
#
# How session_id works:
# - First message: frontend sends no session_id
# - Server generates one automatically using uuid4()
# - Server returns it in the response
# - Frontend stores it and sends it back on every next message
# - This links all messages in one conversation together
# - Without session_id the chatbot has no memory between messages

@app.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    
    # Wrap in try except so server never crashes on bad requests
    try:
        # If frontend did not send a session_id generate one now
        # This happens only on the very first message of a session
        session_id = request.session_id or str(uuid4())
        
        print(f"Chat request - restaurant: {request.restaurant_id} "
              f"session: {session_id}")
        
        # Validate that message is not empty
        # Strip removes spaces from start and end
        if not request.message.strip():
            raise HTTPException(
                status_code=400,
                detail="Message cannot be empty"
            )
        
        # Validate message is not too long
        # Very long messages waste tokens and slow down response
        if len(request.message) > 500:
            raise HTTPException(
                status_code=400,
                detail="Message is too long. Please keep it under 500 characters."
            )
        
        result = await get_answer(
            query=request.message,
            session_id=session_id,
            restaurant_id=request.restaurant_id
        )
        
        # Return structured response to frontend
        return ChatResponse(
            answer=result["answer"],
            dishes=result["dishes"],
            session_id=session_id
        )
    
    except HTTPException:
        # Re-raise HTTP exceptions as they are already formatted
        raise
    
    except Exception as e:
        print(f"Error in chat endpoint: {e}")
        raise HTTPException(
            status_code=500,
            detail="Something went wrong. Please try again."
        )

# STEP 6: Run the server directly with: python api.py
# On Render this block does not run — Render uses its own start command
# This block is only for running locally during development

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        # "api:app" means run the app object inside api.py
        "api:app",
        
        # host 0.0.0.0 means accept requests from any IP
        # needed for deployment — without this only localhost works
        host="0.0.0.0",
        
        # port 8000 is the standard port for FastAPI
        port=8000,
        
        # reload=True means server restarts automatically when 
        # you save changes to the code — only use during development
        reload=True
    )
